---
- hosts: all
  become: yes
  vars:
    dot_repo: 'git@github.com:boris-chernysh/dotfiles.git'
    username: 'boris'
    home_folder: '/home/{{ username }}'
    dot_folder: '{{ home_folder }}/dotfiles'
  tasks:
    - name: Install basic apps
      package:
        name:
          - vim
          - git
          - tmux
          - zsh
        state: present
    - name: Clone dotfiles repo
      git:
        repo: '{{ dot_repo }}'
        dest: '{{ dot_folder }}'
        update: no
    - name: Create symlinks
      file:
        src: '{{ dot_folder }}/{{ item }}'
        dest: '{{ home_folder }}/.{{ item | basename }}'
        state: link
      with_items:
        - tmux.conf
        - zsh/zshrc
