Vagrant.configure("2") do |config|
  config.vm.box = "fe32"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  config.vm.provision :ansible do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "../playbook.yml"
    ansible.extra_vars = {
      "ansible_python_interpreter" => "/usr/bin/python3",
      "username" => "vagrant"
    }
  end
end
